[package]
name = "dropspace_move_contracts"
version = "1.0.0"
authors = []

[addresses]
candymachine_addr="239bd05464ae52dd35f8073b34b33fe4f6080faedea75c1d618535785bfdbf1c"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
